pool:
  vmImage: 'vs2017-win2016'

steps:
- task: stevedower.python.BuildWheel.BuildWheel@1
  inputs:
    dependencies: pip setuptools wheel==0.30.0 cython
    setuppy: 'setup.py'
    signcmd: 'bdist_wheel'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop
    publishLocation: Container
